### ISSUE TITLE
TypeScript[ICON REQUEST]

### ISSUE THREAD

**Issue by yskooo** [artcoholic/akar-icons#101]
**Describe the icon you'd like to be added**
A clear and concise description of what you want to have.
https://www.typescriptlang.org/
**Sample icon**
Attach any samples/screenshots here.
![screencapture-google-search-2022-10-12-23_46_08](https://user-images.githubusercontent.com/90546802/195389193-e7c53ada-93fd-4576-bdfc-e025f810de1a.png)

**Comment by artcoholic** [comment]
@yskooo This is in the library already.
