### ISSUE TITLE
[ICON REQUEST] AR Icon

### ISSUE THREAD

**Issue by GeekMina** [artcoholic/akar-icons#107]
**Describe the icon you'd like to be added**
An icon for AR visualization for 3D models. Can be the shape of a cube with a cellphone 

**Sample icon**
Attach any samples/screenshots here.
![image](https://user-images.githubusercontent.com/104004206/219062388-5bea49c7-e258-41e0-a8ef-ba2921faee82.png)
![image](https://user-images.githubusercontent.com/104004206/219062437-1cc56180-9bbf-4307-bf23-f78d8af70073.png)
![image](https://user-images.githubusercontent.com/104004206/219062549-3f378a7d-a910-4801-a92c-fd2d8ea8afc1.png)
![image](https://user-images.githubusercontent.com/104004206/219062658-b965d815-d484-4ade-9db3-f88e6225a654.png)

**Comment by artcoholic** [comment]
Augmented Reality icon is added to the library.
