### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by paoloricciuti** [artcoholic/akar-icons#108]
Hey i've made a couple of icons for my project and i would love to contribute them so that others can benefit too from them.

Obviosuly i think you would like to take a look at them first so i'll post them here.

However i can't seem to find the correct way to contribute here and i wouldn't want to mess up.

Here's the icons:

|fork|save|
|---|---|
|![fork](https://user-images.githubusercontent.com/26281609/223376937-e145f22f-9799-4f28-b3c0-1f9329b421b3.svg)|![save](https://user-images.githubusercontent.com/26281609/223376939-47716615-6ec7-4463-9a13-50624871952e.svg)|

**Comment by artcoholic** [comment]
@paoloricciuti Thank you! I've tweaked it a bit and added it to the library. Try searching for 'Fork" and "Save".

**Comment by paoloricciuti** [comment]
> @paoloricciuti Thank you! I've tweaked it a bit and added it to the library. Try searching for 'Fork" and "Save".

Wonderful...thank you ;)
