### ISSUE TITLE
[BUG] Warning: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by nirnejak** [artcoholic/akar-icons#111]
While using the library with Next.js getting the following error - `Warning: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

**To Reproduce**
Use the library in the latest Next.js version - 13.3+

**Screenshots**
<img width="1122" alt="Screenshot 2023-04-29 at 4 54 20 AM" src="https://user-images.githubusercontent.com/14347543/235269114-52873518-fef7-43d9-97e3-96fa520ceb74.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Edge(Chromium)
 - Version 112.0.x

**Comment by nirnejak** [comment]
Created a fix here - https://github.com/artcoholic/akar-icons/pull/112

**Comment by artcoholic** [comment]
thank you @nirnejak. PR merged.
