### ISSUE TITLE
[ICON REQUEST] GitLab

### ISSUE THREAD

**Issue by htbrown** [artcoholic/akar-icons#124]
**Describe the icon you'd like to be added**
An icon for GitLab; something based around their standard logo.

**Sample icon**
<img width="154" alt="Screenshot 2024-03-17 at 09 25 15" src="https://github.com/artcoholic/akar-icons/assets/28675646/9dc28803-64b1-4d73-b927-953601659456">
<img width="272" alt="Screenshot 2024-03-17 at 09 25 56" src="https://github.com/artcoholic/akar-icons/assets/28675646/b87836f4-ee15-474a-94d7-e09fcf92228c">

One from [Feather](https://feathericons.com) and two from [FontAwesome](https://fontawesome.com).

Thanks!

**Comment by artcoholic** [comment]
@htbrown icon added.

**Comment by htbrown** [comment]
Thanks!
