### ISSUE TITLE
[ ICON REQUEST ]

### ISSUE THREAD

**Issue by oguzsh** [artcoholic/akar-icons#19]
**Describe the icon you'd like to be added**
Hey!
I think you can add circle and RSS icon for your project. Thx

**Sample icon**
Circle
![image](https://user-images.githubusercontent.com/15168877/108696390-866bb980-7512-11eb-8290-b3a2eea35d9e.png)

RSS
![image](https://user-images.githubusercontent.com/15168877/108696422-91264e80-7512-11eb-9249-5aa0e2c58ef5.png)

**Comment by artcoholic** [comment]
@oguzsh Thank you for the suggestion! They've been added. Let me know if you need anything else.
