### ISSUE TITLE
[ICON REQUEST]

### ISSUE THREAD

**Issue by romannurgaliev** [artcoholic/akar-icons#20]
Backspace icon for the dial

**Sample icon**
Attach any samples/screenshots here.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/40356769/109491518-3a91b500-7abc-11eb-99fb-a9a236bc3133.png">

**Comment by artcoholic** [comment]
@romannurgaliev The backspace icon has been added. Search "backspace" in the app, I've added both stroked and filled format. Thank you for the suggestion!

Let me know if you need anything else.

**Comment by romannurgaliev** [comment]
Thanks a lot @artcoholic! That's probably my first pull request ever
