### ISSUE TITLE
[ICON REQUEST]

### ISSUE THREAD

**Issue by romannurgaliev** [artcoholic/akar-icons#22]
Hi, @artcoholic 

It turned out there is no **Edit** Icon, so this one would be handy.
Thanks in advance

<img width="996" alt="image" src="https://user-images.githubusercontent.com/40356769/110081883-2ea93a00-7dbf-11eb-9765-5637a8d8bfdf.png">

**Comment by artcoholic** [comment]
@romannurgaliev Thanks for the suggestion! We did have a pencil icon that can serve as an edit symbol but it wasn't really clear. So we've added another alternative. Let me know if you need anything else.
