### ISSUE TITLE
[ICON REQUEST] Whatsapp

### ISSUE THREAD

**Issue by digitalblossom** [artcoholic/akar-icons#33]
**Describe the icon you'd like to be added**
Whatsapp icon, as addition to the current social media ones

**Sample icon**
[Sample](https://i.pinimg.com/originals/f7/5d/94/f75d94874d855a7fcfcc922d89ac5e80.png)

**Comment by artcoholic** [comment]
Hi @digitalblossom, Whatsapp icon has been added with the latest PR. Thanks for the suggestion!
