### ISSUE TITLE
[ICON REQUEST]

### ISSUE THREAD

**Issue by maxisme** [artcoholic/akar-icons#35]
**Describe the icon you'd like to be added**
Outlined github logo

**Sample icon**
<img width="56" alt="image" src="https://user-images.githubusercontent.com/16902919/118670398-7d774500-b7ee-11eb-8d77-b8eaed522cf0.png">

**Comment by artcoholic** [comment]
@maxisme Icon added!

**Comment by axelbellahsen** [comment]
Outlined dashboard icon

**Comment by artcoholic** [comment]
@axelbellahsen Please file a new request.
