### ISSUE TITLE
[ICON REQUEST] A FILLED pointer

### ISSUE THREAD

**Issue by unbadfish** [artcoholic/akar-icons#45]
**Describe the icon you'd like to be added**
A filled pointer
Just fill the 'x' in backspace-fill would be great :smile:

**Sample icon**
![Snipaste_2021-08-03_12-17-42](https://user-images.githubusercontent.com/61961263/127957037-9cc5075b-1036-45aa-9bbc-c507f3e123a8.png)
![ScreenshotsSnipaste_2021-08-03_12-17-29](https://user-images.githubusercontent.com/61961263/127957041-04f374ba-e7ef-4d65-b760-3a6728345865.png)

**Comment by unbadfish** [comment]
hi, @artcoholic 
Is it possible to provide 4 icons with the 'arrow' pointing to left, up, right, and down? thanks :smile:

**Comment by artcoholic** [comment]
hi @unbadfish, do you mean having the filled pointer pointing left, up, right, and down? Can you give me a use case example?

> hi, @artcoholic
> Is it possible to provide 4 icons with the 'arrow' pointing to left, up, right, and down? thanks 😄

**Comment by unbadfish** [comment]
I mean these four:
![ScreenshotsSnipaste_2021-08-04_12-36-39](https://user-images.githubusercontent.com/61961263/128122858-d754448d-7e5b-41d0-bbc1-71df6893a884.png)

> Can you give me a use case example?

See this repo: https://github.com/magic-akari/lrc-maker  iosite: https://lrc-maker.github.io/ then click the synchronizer bottom in up-right.
Then you can see the arrow is kind of ugly and required to be replaced. (I would use the right-pointing icon only. :smiley:) 
Before:
![ScreenshotsSnipaste_2021-08-04_12-34-34](https://user-images.githubusercontent.com/61961263/128123463-87161af0-b255-4e2f-b6e3-bd15e44a3e53.png)
After:
![ScreenshotsSnipaste_2021-08-04_12-44-32](https://user-images.githubusercontent.com/61961263/128123398-b77233c7-14ba-4c15-adcd-1f73be24e3e4.png)
Thanks!

**Comment by artcoholic** [comment]
@unbadfish Ok added!
