### ISSUE TITLE
Avoid downloading App dependencies

### ISSUE THREAD

**Issue by brandonchinn178** [artcoholic/akar-icons#47]
When I'm installing `akar-icons`, I notice I'm also downloading `@babel/polyfill`, `fuse.js`, etc. which isn't strictly needed for `src/icons.js`. Installing `akar-icons` shouldn't force me to also install the dependencies needed to run `akaricons.com`.

I recommend using yarn workspaces (or something similar, like lerna) to create subprojects in this repo: `akar-icons` containing just the icon code (the thing that will be deployed to npm), and `akar-icons-app` containing the code to serve `akaricons.com`.

**Comment by artcoholic** [comment]
@brandonchinn178 Thanks for the recommendation! I'm going to look into this. Haven't done the yarn workspaces before.

**Comment by artcoholic** [comment]
@brandonchinn178 I've separate out the app dependencies with the latest update of the NPM package. You should see 0 dependencies. 

Akar icons homepage repo is now [here](https://github.com/artcoholic/akar-icons-app) and I've added Akar icons as icon fonts [here](https://github.com/artcoholic/akar-icons-fonts) if you want to check it out.

**Comment by brandonchinn178** [comment]
Works for me! Thanks!
