### ISSUE TITLE
[ICON REQUEST] Clock

### ISSUE THREAD

**Issue by LewisLarsen** [artcoholic/akar-icons#50]
**Describe the icon you'd like to be added**
While the alarm icon is fantastic, a clock icon would be important to convey the time of something in a clear manner. 

**Sample icon**
https://icon-sets.iconify.design/heroicons-solid/clock/

**Comment by artcoholic** [comment]
@LewisLarsen  Clock icon has been added. Thanks for the suggestion!

<img width="191" alt="Screen Shot 2021-08-10 at 6 17 59 PM" src="https://user-images.githubusercontent.com/6734458/128955082-e2ce1f82-fa85-4bfd-8196-298f4149c9b6.png">
