### ISSUE TITLE
[ICON REQUEST] Group of users

### ISSUE THREAD

**Issue by LewisLarsen** [artcoholic/akar-icons#51]
**Describe the icon you'd like to be added**
A group of users to go with the singular user. Would be brilliant if you could do an icon with two and an icon with three people; perhaps one could be called "friends" and another "group" or something. 

**Sample icon**
https://icon-sets.iconify.design/el/group/

**Comment by artcoholic** [comment]
`People Multiple` and `People Group` have been added. Thanks for the suggestions!

<img width="370" alt="Screen Shot 2021-08-10 at 6 19 09 PM" src="https://user-images.githubusercontent.com/6734458/128955159-ac42b67a-0d09-4a80-ab63-eef150ff5d2a.png">
