### ISSUE TITLE
[BUG] Can't resolve prop-types

### ISSUE THREAD

**Issue by brandonchinn178** [artcoholic/akar-icons#54]
When building my project with `akar-icons`, I get the error message
```
Module not found: Can't resolve 'prop-types'
```

I think you need to add `prop-types` as a dependency. Also, I don't see any errors yet, but you should probably add `react` as a `peerDependency`.

**Comment by artcoholic** [comment]
@brandonchinn178 Thanks for reporting this. Should be fixed with the last push. Try re-installing akar-icons@latest. Let me know if you see any more errors. Thank you!

**Comment by brandonchinn178** [comment]
Works! Thanks!
