### ISSUE TITLE
General Improvements

### ISSUE THREAD

**Issue by brandonchinn178** [artcoholic/akar-icons#55]
A few things (feel free to break these out into separate issues):
- [x] #56
- [x] IMO You should avoid setting `display: block` on the icon element. Icons are not necessarily block elements; someone might want to use them inline (in my case, inside a `<button>`). Currently working around with `svg { display: initial; }`

**Comment by artcoholic** [comment]
@brandonchinn178 
* Good catch! Removed the `id` attribute. I was using this for the app but it's not necessary for the NPM package. Changed it to `class` in the app.
* I was encountering the problem of having extra bottom space in the SVG. The `display: block` was a solution. Would `display: inherit` work? Could you explain more why `display: block` should be avoided? I haven't encountered any problems with my own implementation.
<img width="294" alt="Screen Shot 2021-08-12 at 10 43 58 AM" src="https://user-images.githubusercontent.com/6734458/129244184-14d39147-7b7c-405c-ae0e-af2bc9effd9a.png">

**Comment by brandonchinn178** [comment]
You can add `display: block` in the app, but you shouldnt forcibly add it in the React component. Say if someone wants an inline icon like "hello <plus sign> world", display block would ruin that. In general, component libraries should do the minimum it needs to work, and leave how-it-integrates-with-things-around-it to the caller

**Comment by artcoholic** [comment]
You have a point. I think I was being biased towards my own usage. I just pushed an update (v1.8.8) to address these issues. Thanks again for the suggestions!
