### ISSUE TITLE
[ICON REQUEST] - Delivery/Truck

### ISSUE THREAD

**Issue by jonathanawesome** [artcoholic/akar-icons#58]
**Describe the icon you'd like to be added**
An icon of a truck.

**Sample icon**
_Another_ icon pack's [version of a truck](https://heroicons.dev/?query=truck).

**Comment by artcoholic** [comment]
@jonathanawesome The truck icon has been added to the library. Thanks for the suggestion!

**Comment by jonathanawesome** [comment]
Looks great...thank you!
