### ISSUE TITLE
[ICON REQUEST] Wineglas

### ISSUE THREAD

**Issue by podlebar** [artcoholic/akar-icons#59]
**Describe the icon you'd like to be added**
Would be nice to have a Wineglas Icon

**Sample icon**
<img width="52" alt="Bildschirmfoto 2021-08-18 um 13 21 30" src="https://user-images.githubusercontent.com/342104/129889633-43edae46-4800-44a3-abf0-7ae049323730.png">

**Comment by artcoholic** [comment]
@podlebar The wine-glass has been added to the library. Thanks for the suggestion!
