### ISSUE TITLE
[ICON REQUEST] Globe

### ISSUE THREAD

**Issue by podlebar** [artcoholic/akar-icons#60]
**Describe the icon you'd like to be added**
A nice Globe or World Map Icon would be much appreciated

**Sample icon**
<img width="39" alt="Bildschirmfoto 2021-08-18 um 13 23 14" src="https://user-images.githubusercontent.com/342104/129889871-bdff09a7-bb92-426a-9016-867adb814437.png">

**Comment by artcoholic** [comment]
@podlebar A globe icon is available in the library already. Please use this for now. The sample icon you provided is not in style with Akar icons.
<img width="186" alt="Screen Shot 2021-08-18 at 11 12 56 AM" src="https://user-images.githubusercontent.com/6734458/129975984-b3295597-0a3d-4710-a18d-0113a6f57f33.png">
