### ISSUE TITLE
[BUG] Icon names on website do not match actual CSS classes

### ISSUE THREAD

**Issue by jwu56** [artcoholic/akar-icons#61]
**Describe the bug**
The HTML/CSS snippet offered for each icon does not show the correct class name. For example, for the Arrow Down icon, the real CSS classname is ai-arrow-down, but the class shown is ai-ArrowDown.

**To Reproduce**
1. Go to https://akaricons.com
2. Find and click on an icon
3. Look at class

**Expected behavior**
The correct classname should come up.

**Screenshots**
![image](https://user-images.githubusercontent.com/25115324/130016532-00e5d261-1052-40e2-a8cd-b81d1795eb76.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - 92

**Comment by artcoholic** [comment]
@jwu56 Good catch! It's fixed. Thanks!
