### ISSUE TITLE
[ICON REQUEST]

### ISSUE THREAD

**Issue by Kxffie** [artcoholic/akar-icons#62]
Icons of a cursor (windows, apple, linux)

My website im making would definitely look better with a cursor icon, since its named with the word "Click" and a cursor would make a good icon to show off its use.

**Comment by artcoholic** [comment]
the hand cursor or the arrow point cursor?

**Comment by Kxffie** [comment]
maybe just a cursor, yk how the windows is in "idle" where its the triangle with a stick look

**Comment by Kxffie** [comment]
![image](https://user-images.githubusercontent.com/78885838/132932475-c8af2e5f-5b53-4c46-b068-f705fee0fba7.png)
