### ISSUE TITLE
[ICON REQUEST] Sword

### ISSUE THREAD

**Issue by LewisLarsen** [artcoholic/akar-icons#68]
**Describe the icon you'd like to be added**
Sword - perhaps it should be slightly at an angle :)

**Sample icon**
https://fontawesome.com/v5.15/icons/sword?style=solid

(Thank you for the last icon by the way, you're a star!)

**Comment by artcoholic** [comment]
@LewisLarsen Not a problem. Sword has been added to the library. Search for sword and it should come up.
