### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by michivonah** [artcoholic/akar-icons#77]
**Describe the bug**
The Linkedin icon is not displayed when used as a CSS font. This occurs with version 1 and 2 of the Linkedin icon.

**To Reproduce**
1. Create a new project with akar icons
2. Add the linkedin icon
3. Load the project and look for the missing linkedin icon

**Expected behavior**
I expect the Linkedin logo to be displayed in this case.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows & iOS
 - Browser Chrome & Microsoft Edge

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.3
 - Browser Chrome

**Additional context**

**Comment by artcoholic** [comment]
@michivonah Thanks for pointing this out. I've pushed a fix with a name change. Check out the updated snippet here [www.akaricons.com](url).
