### ISSUE TITLE
[ICON REQUEST] Behance Icon

### ISSUE THREAD

**Issue by nirnejak** [artcoholic/akar-icons#78]
**Describe the icon you'd like to be added**
Behance Icon

**Sample icon**
![behance-brands](https://user-images.githubusercontent.com/14347543/154831120-1315e99e-0271-4496-abb4-fef6d89ff4a0.svg)

**Comment by artcoholic** [comment]
@nirnejak behance icon added. Please updated your package to akar-icons@latest. Thank you.

**Comment by nirnejak** [comment]
Thanks @artcoholic 🙌
