### ISSUE TITLE
[BUG] Unable to import the icons in the latest version

### ISSUE THREAD

**Issue by nirnejak** [artcoholic/akar-icons#80]
**Describe the bug**
The new version seems broken, not able to import any icons. 

```
Module '"akar-icons"' has no exported member 'LinkedinFill'.ts(2305)
```

**To Reproduce**
Unable to import the Icons in the latest version

**Expected behavior**
Should be able to import the Icons

**Screenshots**
![Screen Shot 2022-03-12 at 4 07 45 AM](https://user-images.githubusercontent.com/14347543/157984081-4a99d03e-07c4-4da5-a34a-74d486727e53.png)
![Screen Shot 2022-03-12 at 4 07 59 AM](https://user-images.githubusercontent.com/14347543/157984089-f2be0f61-b85e-4507-ac0c-787e75ee9139.png)

**Desktop (please complete the following information):**
 - OS: macOS Latest
 - Browser Edge
 - Version 99

**Comment by artcoholic** [comment]
Hi @nirnejak, thanks for reporting this. Can you try re-installing akar-icons@latest? I did several rollbacks and pushed a new package version. Let me know if you still see this error. Thank you.

**Comment by nirnejak** [comment]
@artcoholic Updated to latest, working now, Thanks a lot
