### ISSUE TITLE
[ICON REQUEST] Music

### ISSUE THREAD

**Issue by htbrown** [artcoholic/akar-icons#90]
**Describe the icon you'd like to be added**
An icon depicting something like music notes, CDs etc.

**Sample icon**
![image](https://user-images.githubusercontent.com/28675646/173255203-2ad22ca6-0eee-4670-9f5f-35a2c0532c26.png)
![image](https://user-images.githubusercontent.com/28675646/173255210-01b24103-71d1-4c3f-a61a-52daed0dc9ca.png)
FontAwesome equivalents.

**Comment by artcoholic** [comment]
@htbrown These icons have been added to the library. Please update akar-icons@latest.
