### ISSUE TITLE
[ICON REQUEST] mastodon-fill

### ISSUE THREAD

**Issue by Morpheus636** [artcoholic/akar-icons#95]
**Describe the icon you'd like to be added**
An icon of the [mastodon](https://joinmastodon.org/) social network's logo. 

**Sample icon**
Attach any samples/screenshots here.
Their press kit here: https://joinmastodon.org/press-kit.zip

Specifically, the simple logotype would be great.

**Comment by artcoholic** [comment]
@Morpheus636 This icon has been added to the library. Thank you.
