### ISSUE TITLE
[ICON REQUEST] Unsplash Icon

### ISSUE THREAD

**Issue by nirnejak** [artcoholic/akar-icons#99]
**Describe the icon you'd like to be added**
Unsplash Icon

**Sample icon**
Attach any samples/screenshots here.

![unsplash-2](https://user-images.githubusercontent.com/14347543/190601352-3dd7f150-97b7-4de4-8535-c53e011ad5fe.svg)

**Comment by artcoholic** [comment]
@nirnejak unsplash logo icon has been added to the library.
